### ISSUE TITLE
Respect channel slow mode timers

### ISSUE THREAD

**Issue by 4monkw84** [ethankrein/Trickcord-Treat-Sniper#11]
Server I've been using the bot on has enabled 10 minute slow mode timers on the two channels the bot is active in, and the bot has a tendency to still attempt to reply upwards of 2 minutes after and force another cooldown resulting in wasted attempts.

Means I have to babysit the bot, toggling it on and off every 10 minutes to minimise the wasted attempts.

**Comment by latelylk** [comment]
I'll look into this when I have some free time. For now, if you're using the spam feature, try setting `minSpamDelay` in config.yaml to `600000` (10 minutes) and `maxSpamDelay` to a little above that.

**Comment by latelylk** [comment]
Hi there, could you be more specific about your issue? 

I don't understand what you mean when you say this:
> force another cooldown resulting in wasted attempts.

What exactly is happening? To my knowledge discord doesn't penalize you for trying to send messages in a channel with slowmode.

**Comment by 4monkw84** [comment]
The sniper bot still attempts to snipe discord bot messages several minutes after they appear. So, for example, should I have 2 minutes left on my channel timer and the discord bot sends a message, the sniper will keep trying to reply for the entirety of those 2 minutes, inevitably succeeding at the end and starting the 10 minute timer again by wasting an attempt.

Does that make more sense? Trying to find a better way to explain it but I suck at explanations

**Comment by latelylk** [comment]
It made enough sense for me to do some testing. For whatever reason, Eris insists on waiting to send the created message if it can't send it. There also does not appear to be a way to detect slowmode with Eris (likely because real bots are exempt.)

I added an option, `slowmode`, to the config in the latest commit which should address your issue.

Without a way to detect slowmode in the channel, I instead opted to create a debounce. Unfortunately, this means that when the bot sends a message it pauses detection in all channels and all servers for the duration of the `slowmodeTimer` config option. I wish there was a more versatile way to implement this, but unfortunately this is just the limit of the Eris library.

Hope this update at least somewhat solves your issue!
